<div class="col-mb-12 col-tb-8 col-tb-offset-2" role="form">
	<form action="#" method="post" enctype="application/x-www-form-urlencoded">
		<ul class="typecho-option" id="typecho-option-item-logoUrl-0">
			<li>
				<label class="typecho-label" for="logoUrl-0-1">站点LOGO地址</label>
				<input id="logoUrl-0-1" name="logoUrl" type="text" class="text" value="" />
				<p class="description">在这里填入一个图片URL地址, 以在网站标题前加上一个LOGO</p>
			</li>
		</ul>
		<ul class="typecho-option" id="typecho-option-item-sidebarBlock-1">
			<li>
				<label class="typecho-label">侧边栏显示</label>
				<span class="multiline">
					<input name="sidebarBlock[]" type="checkbox" value="ShowRecentPosts" id="sidebarBlock-ShowRecentPosts" checked="true" />
					<label for="sidebarBlock-ShowRecentPosts">显示最新文章</label>
				</span>
				<span class="multiline">
					<input name="sidebarBlock[]" type="checkbox" value="ShowRecentComments" id="sidebarBlock-ShowRecentComments" checked="true" />
					<label for="sidebarBlock-ShowRecentComments">显示最近回复</label>
				</span>
				<span class="multiline">
					<input name="sidebarBlock[]" type="checkbox" value="ShowCategory" id="sidebarBlock-ShowCategory" checked="true" />
					<label for="sidebarBlock-ShowCategory">显示分类</label>
				</span>
				<span class="multiline">
					<input name="sidebarBlock[]" type="checkbox" value="ShowArchive" id="sidebarBlock-ShowArchive" checked="true" />
					<label for="sidebarBlock-ShowArchive">显示归档</label>
				</span>
				<span class="multiline">
					<input name="sidebarBlock[]" type="checkbox" value="ShowOther" id="sidebarBlock-ShowOther" checked="true" />
					<label for="sidebarBlock-ShowOther">显示其它杂项</label>
				</span>
			</li>
		</ul>
		<ul class="typecho-option typecho-option-submit" id="typecho-option-item--2">
			<li>
				<button type="submit" class="btn primary">保存设置</button>
			</li>
		</ul>
	</form>
</div>