<div class="typecho-table-wrap">
	<table class="typecho-list-table typecho-theme-list">
		<colgroup>
			<col width="35%" />
			<col />
		</colgroup>

		<thead>
		<th>截图</th>
		<th>详情</th>
		</thead>

		<tbody>
		<tr id="theme-default" class="current">
			<td valign="top"><img src="http://typecho.git.com/usr/themes/default/screenshot.png" alt="default" /></td>
			<td valign="top">
				<h3>Typecho Replica Theme</h3>
				<cite>
					作者: <a href="http://typecho.org">Typecho Team</a> &nbsp;&nbsp; 版本: 1.2 </cite>
				<p>这是 Typecho 0.9 系统的一套默认皮肤</p>
			</td>
		</tr>
		</tbody>
	</table>
</div>
