<div class="typecho-edit-theme">
	<div class="col-mb-12 col-tb-8 col-9 content">
		<form method="post" name="theme" id="theme" action="#">
			<label for="content" class="sr-only">编辑源码</label>
			<textarea name="content" id="content" class="w-100 mono" ></textarea>
			<p class="submit">
				<input type="hidden" name="theme" value="default" />
				<input type="hidden" name="edit" value="index.php" />
				<button type="submit" class="btn primary">保存文件</button>
			</p>
		</form>
	</div>
	<ul class="col-mb-12 col-tb-4 col-3">
		<li><strong>模板文件</strong></li>
		<li><a href="#">404.php</a></li>
		<li><a href="#">archive.php</a></li>
		<li><a href="#">comments.php</a></li>
		<li><a href="#">footer.php</a></li>
		<li><a href="#">functions.php</a></li>
		<li><a href="#">header.php</a></li>
		<li class="current"><a href="#">index.php</a></li>
		<li><a href="#">page.php</a></li>
		<li><a href="#">post.php</a></li>
		<li><a href="#">sidebar.php</a></li>
		<li><a href="#">grid.css</a></li>
		<li><a href="#">style.css</a></li>
	</ul>
</div>