<div id="content" role="main">
    <div class="post type-post status-publish format-standard has-post-thumbnail hentry category-wordpress category-tutorial">
        <div class="c-top2">
            {% set modifyTime = explode('-', explode(' ', article['modify_time'])[0]) %}
            <div class="datetime">{{modifyTime[0]}}<br>{{modifyTime[1]}}-{{modifyTime[2]}}</div>
            <header class="tit">
                <h1 class="entry-title">{{article['title']}}</h1>
                <aside class="entry-meta iititle2">
                    <span>
                        <i class="icon-user icon-large"></i>
                        <a href="" title="Marser" rel="author">Marser</a>
                    </span>
                    <span>
                        {% if article['categorys'] is not empty %}
                            <i class="icon-folder-open icon-large"></i>
                            {% for ck,cv in article['categorys'] %}
                                {% if ck==0 %}
                                    <a href="#" rel="category tag">{{cv['category_name']}}</a>
                                {% else %}
                                    ,<a href="#" rel="category tag">{{cv['category_name']}}</a>
                                {% endif %}
                            {% endfor %}
                        {% endif %}
                    </span>
                    <span>
                        <i class="icon-eye-open icon-large"></i> 围观<i id="number">{{article['view_number']}}</i>次
                    </span>
                    <span>
                        <i class="icon-comment-alt icon-large"></i>
                        <a href="">评论</a>
                    </span>
                    <span>
                        <i class="icon-zoom-in icon-large"></i> 字体：
                        <a href="javascript:;" onclick="checkFontSize(18)">大</a>
                        <a href="javascript:;" onclick="checkFontSize(16)">中</a>
                        <a href="javascript:;" onclick="checkFontSize(14)">小</a>
                    </span>
                </aside>
            </header>
            <div class="cls"></div>
        </div>
        <article class="entry-content">
            {{article['content']}}
            <div class="content-tags iititle2">
                <aside class="cb_bq">
                    {% if article['tags'] is not empty %}
                        标签：
                        {% for tk,tv in article['tags'] %}
                            {% if tk==0 %}
                                <span><a href="#" rel="tag">{{tv['tag_name']}}</a></span>
                            {% else %}
                                ,<span><a href="#" rel="tag">{{tv['tag_name']}}</a></span>
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                </aside>
                <div class="cls"></div>
            </div>
            <div class="loc_link">
                <ul>
                    <li>本站文章除注明转载外，均为本站原创</li>
                    <li>欢迎任何形式的转载，但请务必注明出处，尊重他人劳动</li>
                    <li>转载请注明：文章转载自：Marser [http://www.marser.cn/]</li>
                    <li>本文标题：{{article['title']}}</li>
                    <li>本文固定链接：
                        <a href="{{article['aid']}}" rel="bookmark" title="{{article['title']}}">
                            http://www.marser.cn/archives/124/
                        </a>
                    </li>
                </ul>
            </div>
            <div class="cls"></div>
        </article>
    </div>
    <div id="nav-below" class="navigation">
        <div class="nav-previous">
            {% if prevAritcle is not empty %}
                <a href="" rel="next">
                    <i class="icon-arrow-left"></i>
                    {{prevArticle['title']}}
                </a>
            {% else %}
                <a href="javascript:void(0);" rel="prev">
                    <i class="icon-arrow-left"></i>
                    已经是第一篇啦
                </a>
            {% endif %}
        </div>
        <div class="nav-next">
            {% if nextArticle is not empty %}
                <a href="" rel="next">
                    {{nextArticle['title']}}
                    <i class="icon-arrow-right"></i>
                </a>
            {% else %}
                <a href="javascript:void(0);" rel="next">
                    已经是最后一篇啦
                    <i class="icon-arrow-right"></i>
                </a>
            {% endif %}
        </div>
    </div>
    <div class="cls"></div>
    <div class="relatedposts">
        <h3 class="widget-title"><i class="icon-warning-sign"></i> 您可能还会对这些文章感兴趣！</h3>
        <ul>
            <li><a href="http://www.frontopen.com/2898.html" rel="bookmark" title="详细阅读 wordpress后台打开缓慢的临时解决方法">wordpress后台打开缓慢的临时解决方法</a></li>
            <li><a href="http://www.frontopen.com/2501.html" rel="bookmark" title="详细阅读 frontopen主题v1.4.04.05更新升级日志">frontopen主题v1.4.04.05更新升级日志</a></li>
            <li><a href="http://www.frontopen.com/2421.html" rel="bookmark" title="详细阅读 关于frontopen v140330更新后“提请审批”解决方案">关于frontopen v140330更新后“提请审批”解决方案</a></li>
            <li><a href="http://www.frontopen.com/2357.html" rel="bookmark" title="详细阅读 调用wordpress自带jquery库的方法与注意事项">调用wordpress自带jquery库的方法与注意事项</a></li>
            <li><a href="http://www.frontopen.com/2349.html" rel="bookmark" title="详细阅读 为wordpress数据库添加数据表的方法">为wordpress数据库添加数据表的方法</a></li>
            <li><a href="http://www.frontopen.com/2222.html" rel="bookmark" title="详细阅读 关于frontopen主题中发布音乐的使用方法">关于frontopen主题中发布音乐的使用方法</a></li>
            <li><a href="http://www.frontopen.com/2045.html" rel="bookmark" title="详细阅读 让文章标题链接添加动态载入效果">让文章标题链接添加动态载入效果</a></li>
            <li><a href="http://www.frontopen.com/2025.html" rel="bookmark" title="详细阅读 frontopen主题v1.4.03.08更新升级日志">frontopen主题v1.4.03.08更新升级日志</a></li>
        </ul>
        <div class="cls"></div>
    </div>
</div>