<div class="breadcrumbs" id="breadcrumbs">
    <ul class="breadcrumb">
        <li>
            <i class="icon-home home-icon"></i>
            <a href="{{ url(modulePathinfo~'/dashboard/index') }}">控制面板</a>
        </li>
        <li>
            <a href="{{ url(modulePathinfo~'/categorys/index') }}">分类管理</a>
        </li>
    </ul>
</div>
<div class="page-content">
    <div class="col-lg-12">
        <div class="btn-panel">
            <a href="{{ url(modulePathinfo~'/categorys/write') }}" class="btn btn-success btn-sm" role="button">新增分类</a>
            <a href="{{ url(modulePathinfo~'/categorys/refresh') }}" class="btn btn-pink btn-sm" role="button">清除分类缓存</a>
        </div>
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">分类列表</h3>
            </div>
            <div class="panel-body" id="category-list-box">
                <table class="table tree-grid table-bordered table-condensed table-hover" id="test-table">
                    <thead>
                        <tr>
                            <th>分类名称</th>
                            <th>缩略名</th>
                            <th>排序</th>
                            <th>更新时间</th>
                            <th>&nbsp;</th>
                        </tr>
                    </thead>
                    {% if categoryList is not empty %}
                        <tbody>
                            {% for category in categoryList %}
                                {% if category['parent_cid'] is not empty %}
                                    <tr class="treegrid-{{category['cid']}} treegrid-parent-{{category['parent_cid']}}">
                                {% else %}
                                    <tr class="treegrid-{{category['cid']}}">
                                {% endif %}
                                    <td>
                                        <a href="{{ url(modulePathinfo~'/categorys/write?cid='~category['cid']) }}" title="编辑分类">
                                            {{ category['category_name'] }}
                                        </a>
                                    </td>
                                    <td>{{ category['slug'] }}</td>
                                    <td>
                                        <a href="javascript:void(0);" class="category-sort-block" data-name="sort"
                                           data-url="{{ url(modulePathinfo~'/categorys/savesort') }}"
                                           data-pk="{{category['cid']}}" data-type="text"
                                           data-placement="top" data-title="修改分类排序">
                                            {{ category['sort'] }}
                                        </a>
                                    </td>
                                    <td>{{ date('Y-m-d H:i:s', category['modify_time']) }}</td>
                                    <td>
                                        <a class="btn btn-xs btn-success" href="{{ url(modulePathinfo~'/categorys/write?parentcid='~category['cid']) }}">
                                            <i class="icon-plus bigger-120"></i>
                                        </a>
                                        <a class="btn btn-xs btn-info" href="{{ url(modulePathinfo~'/categorys/write?cid='~category['cid']) }}">
                                            <i class="icon-pencil bigger-120"></i>
                                        </a>
                                        <button class="btn btn-xs btn-danger delete-category" data-url="{{ url(modulePathinfo~'/categorys/delete?cid='~category['cid']) }}">
                                            <i class="icon-trash bigger-120"></i>
                                        </button>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    {% else %}
                        <tbody>
                            <tr>
                                <td colspan="8">暂无数据</td>
                            </tr>
                        </tbody>
                    {% endif %}
                </table>
            </div>
        </div>
    </div>
</div>