<div class="main">
	<div class="body container">
		<div class="typecho-page-title">
			<h2>管理独立页面<a href="#">新增</a></h2>
		</div>
		<div class="row typecho-page-main" role="main">
			<div class="col-mb-12 typecho-list">
				<div class="typecho-list-operate clearfix">
					<form method="get">
						<div class="operate">
							<label>
								<i class="sr-only">全选</i>
								<input type="checkbox" class="typecho-table-select-all" />
							</label>
							<div class="btn-group btn-drop">
								<button class="btn dropdown-toggle btn-s" type="button">
									<i class="sr-only">操作</i>选中项
									<i class="i-caret-down"></i>
								</button>
								<ul class="dropdown-menu">
									<li><a lang="你确认要删除这些页面吗?" href="#">删除</a></li>
								</ul>
							</div>
						</div>

						<div class="search" role="search">
							<input type="text" class="text-s" placeholder="请输入关键字" value="" name="keywords" />
							<button type="submit" class="btn btn-s">筛选</button>
						</div>
					</form>
				</div>

				<form method="post" name="manage_pages" class="operate-form">
					<div class="typecho-table-wrap">
						<table class="typecho-list-table">
							<colgroup>
								<col width="20"/>
								<col width="6%"/>
								<col width="30%"/>
								<col width="30%"/>
								<col width=""/>
								<col width="16%"/>
							</colgroup>
							<thead>
							<tr class="nodrag">
								<th> </th>
								<th> </th>
								<th>标题</th>
								<th>缩略名</th>
								<th>作者</th>
								<th>日期</th>
							</tr>
							</thead>
							<tbody>
							<tr id="page-2">
								<td><input type="checkbox" value="2" name="cid[]"/></td>
								<td><a href="#" class="balloon-button size-1">0</a></td>
								<td>
									<a href="#">关于</a>
									<a href="#" title="浏览 关于"><i class="i-exlink"></i></a>
								</td>
								<td>start-page</td>
								<td>admin</td>
								<td>5月12日</td>
							</tr>
							</tbody>
						</table>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
