
<div class="main">
	<div class="body container">
		<div class="typecho-page-title">
			<h2>管理文件</h2>
		</div>
		<div class="row typecho-page-main" role="main">
			<div class="col-mb-12">
				<div class="typecho-list-operate clearfix">
					<form method="get">
						<div class="operate">
							<label><i class="sr-only">全选</i><input type="checkbox" class="typecho-table-select-all" /></label>
							<div class="btn-group btn-drop">
								<button class="btn dropdown-toggle btn-s" type="button">
									<i class="sr-only">操作</i>选中项 <i class="i-caret-down"></i>
								</button>
								<ul class="dropdown-menu">
									<li><a lang="你确认要删除这些文件吗?" href="#">删除</a></li>
								</ul>
								<button class="btn btn-s btn-warn btn-operate" href="#" lang="您确认要清理未归档的文件吗?">清理未归档文件</button>
							</div>
						</div>
						<div class="search" role="search">
							<input type="text" class="text-s" placeholder="请输入关键字" value="" onclick="value='';name='keywords';" />
							<button type="submit" class="btn btn-s">筛选</button>
						</div>
					</form>
				</div><!-- end .typecho-list-operate -->

				<form method="post" name="manage_medias" class="operate-form">
					<div class="typecho-table-wrap">
						<table class="typecho-list-table draggable">
							<colgroup>
								<col width="20"/>
								<col width="6%"/>
								<col width="30%"/>
								<col width=""/>
								<col width="30%"/>
								<col width="16%"/>
							</colgroup>
							<thead>
							<tr>
								<th> </th>
								<th> </th>
								<th>文件名</th>
								<th>上传者</th>
								<th>所属文章</th>
								<th>发布日期</th>
							</tr>
							</thead>
							<tbody>
							<tr>
								<td colspan="6"><h6 class="typecho-list-table-title">没有任何文件</h6></td>
							</tr>
							</tbody>
						</table>
					</div>
				</form>

				<div class="typecho-list-operate clearfix">
					<form method="get">
						<div class="operate">
							<label><i class="sr-only">全选</i><input type="checkbox" class="typecho-table-select-all" /></label>
							<div class="btn-group btn-drop">
								<button class="btn dropdown-toggle btn-s" type="button">
									<i class="sr-only">操作</i>选中项 <i class="i-caret-down"></i>
								</button>
								<ul class="dropdown-menu">
									<li><a lang="你确认要删除这些文件吗?" href="#">删除</a></li>
								</ul>
							</div>
							<button class="btn btn-s btn-warn btn-operate" href="@" lang="您确认要清理未归档的文件吗?">清理未归档文件</button>
						</div>

					</form>
				</div>
			</div>
		</div>
	</div>
</div>
