<div class="breadcrumbs" id="breadcrumbs">
    <ul class="breadcrumb">
        <li>
            <i class="icon-home home-icon"></i>
            <a href="{{ url(modulePathinfo~'/dashboard/index') }}">控制面板</a>
        </li>
        <li>
            <a href="{{ url(modulePathinfo~'/articles/index') }}">文章管理</a>
        </li>
        <li>
            <a href="{{ url(modulePathinfo~'/articles/write') }}">新增文章</a>
        </li>
    </ul>
</div>
<div class="page-content">
    <form action="{{url(modulePathinfo~'/articles/publish')}}" method="post" class="form-horizontal" id="save-archive-form">
        <div class="col-lg-6">
            <div class="form-group">
                <label for="archive-title" class="col-sm-2 control-label">文章标题</label>
                <div class="col-sm-9">
                    <input type="text" name="title" class="form-control" id="title" {% if article is not empty %}value="{{article['title']}}"{% endif %}>
                </div>
            </div>
            <div class="form-group">
                <label for="archive-content" class="col-sm-2 control-label">内容</label>
                <div class="col-sm-9">
                    <textarea id="article-content" name="content">{% if article is not empty %}{{article['markdown']}}{% endif %}</textarea>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-5">
                    {% if article is not empty %}
                        <input type="hidden" name="aid" value="{{article['aid']}}" />
                    {% endif %}
                    <input type="hidden" name="status" id="status" />
                    <button type="button" class="btn btn-info btn-sm" data-status="1" id="save-articles-btn">发布文章</button>
                    <button type="button" class="btn btn-sm" data-status="2" id="save-articles-draft-btn">保存草稿</button>
                </div>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="form-group">
                <label for="archive-time" class="col-sm-2 control-label">发布时间</label>
                <div class="col-sm-5">
                    <input type="text" name="time" id="archive-time" class="form-control Wdate" {% if article is not empty %}value="{{article['modify_time']}}"{% endif %} />
                </div>
            </div>
            <div class="form-group ">
                <label for="archive-category" class="col-sm-2 control-label">所属分类</label>
                <div class="col-sm-9">
                    <div class="archive-category-list">
                        <ul>
                            {% for value in categoryList %}
                                <li>
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" name="category[]" value="{{value['cid']}}"
                                                {% if article is not empty and cids[article['aid']] is not empty %}
                                                   {% for cv in cids[article['aid']] %}
                                                        {% if cv == value['cid'] %}
                                                            checked="checked"
                                                            {% break %}
                                                        {% endif %}
                                                   {% endfor %}
                                                {% endif %}
                                            />{{value['category_name']}}
                                        </label>
                                    </div>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label for="archive-tags" class="col-sm-2 control-label">标签</label>
                <div class="col-sm-9">
                    <input type="text" name="tags" class="form-control" id="archive-tags" placeholder="请填写标签" />
                </div>
            </div>
        </div>
    </form>
</div>
<link rel="stylesheet" href="{{ assetsUrl }}/simplemde/css/simplemde.min.css?_v={{ assetsVersion }}" />
<link rel="stylesheet" href="{{ assetsUrl }}/simplemde/css/font-awesome.min.css?_v={{ assetsVersion }}" />
<script src="{{ assetsUrl }}/simplemde/js/simplemde.min.js?_v={{ assetsVersion }}"></script>
<link rel="stylesheet" href="{{ assetsUrl }}/tagsinput/jquery.tagsinput.css?_v={{ assetsVersion }}" />
<script src="{{ assetsUrl }}/tagsinput/jquery.tagsinput.js"></script>
<script src="{{ assetsUrl }}/my97datepicker/WdatePicker.js"></script>
<script>
    var simplemde = new SimpleMDE({
        element:document.getElementById('article-content'),
        autoDownloadFontAwesome:false,
        styleSelectedText:false,
        spellChecker:false
    });
    $('#archive-time').on('click', function(){
        WdatePicker({
            dateFmt:'yyyy-MM-dd HH:mm'
        });
    });
    $('#archive-tags').tagsInput({
        'defaultText':'请填写标签',
        'width':'100%',
        'height':'auto'
    });
    $('#save-articles-btn, #save-articles-draft-btn').on('click', function(){
        var title = $.trim($('#title').val());
        if(typeof title == 'undefined' || title == false){
            tips_message('请填写文章标题');
            return false;
        }

        var content = simplemde.value();
        if(typeof content == 'undefined' || content == false){
            tips_message('请填写文章内容');
            return false;
        }

        var category = new Array();
        $('input[name="category[]"]').each(function(){
            if($(this).is(':checked')){
                category.push($(this).val());
            }
        });
        if(category.length == 0){
            tips_message('请选择文章分类');
            return false;
        }

        var tags = $.trim($('#archive-tags').val());
        if(typeof tags == 'undefined' || tags == false){
            tips_message('请填写标签');
            return false;
        }

        var status = $(this).attr('data-status');
        $('#status').val(status);
        $('#save-archive-form').submit();
    });
    {% if article is not empty and tags is not empty %}
        {% for tv in tags %}
            $("#archive-tags").addTag('{{tv['tag_name']}}');
        {% endfor %}
    {% endif %}
</script>