<!DOCTYPE HTML>
<html class="no-js">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">
    <meta name="renderer" content="webkit">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{title}}</title>
    <meta name="robots" content="noindex, nofollow">
    <link rel="stylesheet" href="{{ assetsUrl }}/css/normalize.css?v={{ assetsVersion }}" />
    <link rel="stylesheet" href="{{ assetsUrl }}/css/style.css?v={{ assetsVersion }}" />
    <!--[if lt IE 9]>
    <script type="text/javascript" src="{{ assetsUrl }}/js/html5shiv.js?v={{ assetsVersion }}"></script>
    <script type="text/javascript" src="{{ assetsUrl }}/js/respond.js?v={{ assetsVersion }}"></script>
    <![endif]-->
</head>
<body>
    <!--[if lt IE 9]>
    <div class="message error browsehappy" role="dialog">当前网页 <strong>不支持</strong> 你正在使用的浏览器. 为了正常的访问, 请 <a href="http://browsehappy.com/">升级你的浏览器</a></div>
    <![endif]-->
    <div class="typecho-login-wrap padding-top-per8">
        <div class="typecho-login">
            <form action="{{ url(modulePathinfo~"/passport/login") }}" method="post" id="login_form" role="form">
                <p>
                    <label for="username" class="sr-only">用户名</label>
                    <input type="text" id="username" name="username" value="" placeholder="用户名" class="text-l w-100" autofocus />
                </p>
                <p>
                    <label for="password" class="sr-only">密码</label>
                    <input type="password" id="password" name="password" class="text-l w-100" placeholder="密码" />
                </p>
                <p class="submit">
                    <button type="button" class="btn btn-l w-100 primary" id="submit_btn">登录</button>
                    <input type="hidden" name="referer" value="" />
                </p>
            </form>
        </div>
    </div>
    <script type="text/javascript" src="{{ assetsUrl }}/js/jquery.js?v={{ assetsVersion }}"></script>
    <script type="text/javascript">
        $(document).ready(function(){
            $('#username').focus();
            $('#submit_btn').on('click', function(){
                $('#login_form').submit();
            });
        });
    </script>
    {{ partial("public/message") }}
</body>
</html>