<div class="breadcrumbs" id="breadcrumbs">
    <ul class="breadcrumb">
        <li>
            <i class="icon-home home-icon"></i>
            <a href="{{ url(modulePathinfo~'/dashboard/index') }}">控制面板</a>
        </li>
        <li>
            <a href="{{ url(modulePathinfo~'/options/base') }}">站点管理</a>
        </li>
    </ul>
</div>
<div class="page-content">
    <div class="page-header">
        <h1>
            <a href="{{ url(modulePathinfo~'/options/base') }}">站点管理</a>
            <small>
                <i class="icon-double-angle-right"></i>
                站点设置
            </small>
        </h1>
    </div>
    <div class="col-lg-12">
        <form action="{{url(modulePathinfo~'/options/savebase')}}" method="post" class="form-horizontal" id="base-options-form">
            <div class="form-group">
                <label for="site-name" class="col-sm-2 control-label">站点名称</label>
                <div class="col-sm-8">
                    <input type="text" name="siteName" value="{% if options is not empty %}{{options['site_name']['op_value']}}{% endif %}"
                           class="form-control" id="site-name" placeholder="请填写站点名称">
                    <span class="form-tips">站点名称由中英文字符、数字、下划线和横杠组成</span>
                </div>
            </div>
            <div class="form-group ">
                <label for="site-url" class="col-sm-2 control-label">站点地址</label>
                <div class="col-sm-8">
                    <input type="text" name="siteUrl" value="{% if options is not empty %}{{options['site_url']['op_value']}}{% endif %}"
                           class="form-control" id="site-url" placeholder="http://">
                </div>
            </div>
            <div class="form-group">
                <label for="site-keywords" class="col-sm-2 control-label">关键词</label>
                <div class="col-sm-8">
                    <input type="text" name="keywords" value="{% if options is not empty %}{{options['site_keywords']['op_value']}}{% endif %}"
                           class="form-control" id="site-keywords" placeholder="请填写站点关键词" />
                    <span class="form-tips">用于SEO。多个关键字间用逗号","分隔</span>
                </div>
            </div>
            <div class="form-group">
                <label for="site-description" class="col-sm-2 control-label">站点描述</label>
                <div class="col-sm-8">
                    <input type="text" name="description" value="{% if options is not empty %}{{options['site_description']['op_value']}}{% endif %}"
                           class="form-control" id="site-description" placeholder="请填写站点描述" />
                    <span class="form-tips">用于SEO</span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-5">
                    <button type="submit" id="base-options-btn" class="btn btn-info btn-sm">保存设置</button>
                </div>
            </div>
        </form>
    </div>
</div>