<div class="main">
	<div class="body container">
		<div class="typecho-page-title">
			<h2>基本设置</h2>
		</div>
		<div class="row typecho-page-main" role="form">
			<div class="col-mb-12 col-tb-8 col-tb-offset-2">
				<form action="#" method="post" enctype="application/x-www-form-urlencoded">
					<ul class="typecho-option" id="typecho-option-item-title-0">
						<li>
							<label class="typecho-label" for="title-0-1">站点名称</label>
							<input id="title-0-1" name="title" type="text" class="w-100" value="" />
							<p class="description">站点的名称将显示在网页的标题处.</p>
						</li>
					</ul>
					<ul class="typecho-option" id="typecho-option-item-siteUrl-1">
						<li>
							<label class="typecho-label" for="siteUrl-0-2">站点地址</label>
							<input id="siteUrl-0-2" name="siteUrl" type="text" class="w-100 mono" value="" />
							<p class="description">站点地址主要用于生成内容的永久链接.</p>
						</li>
					</ul>
					<ul class="typecho-option" id="typecho-option-item-description-2">
						<li>
							<label class="typecho-label" for="description-0-3">站点描述</label>
							<input id="description-0-3" name="description" type="text" class="text" value="" />
							<p class="description">站点描述将显示在网页代码的头部.</p>
						</li>
					</ul>
					<ul class="typecho-option" id="typecho-option-item-keywords-3">
						<li>
							<label class="typecho-label" for="keywords-0-4">关键词</label>
							<input id="keywords-0-4" name="keywords" type="text" class="text" value="php,phalcon,blog" />
							<p class="description">请以半角逗号 "," 分割多个关键字.</p>
						</li>
					</ul>
					<ul class="typecho-option" id="typecho-option-item-allowRegister-4">
						<li>
							<label class="typecho-label">是否允许注册</label>
							<span>
							<input name="allowRegister" type="radio" value="0" id="allowRegister-0" checked="true" />
							<label for="allowRegister-0">不允许</label>
							</span>
							<span>
							<input name="allowRegister" type="radio" value="1" id="allowRegister-1" />
							<label for="allowRegister-1">允许</label>
							</span>
							<p class="description">允许访问者注册到你的网站, 默认的注册用户不享有任何写入权限.</p>
						</li>
					</ul>
					<ul class="typecho-option" id="typecho-option-item-timezone-5">
						<li>
							<label class="typecho-label" for="timezone-0-6">时区</label>
							<select name="timezone" id="timezone-0-6">
								<option value="0">格林威治(子午线)标准时间 (GMT)</option>
								<option value="3600">中欧标准时间 阿姆斯特丹,荷兰,法国 (GMT +1)</option>
								<option value="7200">东欧标准时间 布加勒斯特,塞浦路斯,希腊 (GMT +2)</option>
								<option value="10800">莫斯科时间 伊拉克,埃塞俄比亚,马达加斯加 (GMT +3)</option>
								<option value="14400">第比利斯时间 阿曼,毛里塔尼亚,留尼汪岛 (GMT +4)</option>
								<option value="18000">新德里时间 巴基斯坦,马尔代夫 (GMT +5)</option>
								<option value="21600">科伦坡时间 孟加拉 (GMT +6)</option>
								<option value="25200">曼谷雅加达 柬埔寨,苏门答腊,老挝 (GMT +7)</option>
								<option value="28800" selected="true">北京时间 香港,新加坡,越南 (GMT +8)</option>
								<option value="32400">东京平壤时间 西伊里安,摩鹿加群岛 (GMT +9)</option>
								<option value="36000">悉尼关岛时间 塔斯马尼亚岛,新几内亚 (GMT +10)</option>
								<option value="39600">所罗门群岛 库页岛 (GMT +11)</option>
								<option value="43200">惠灵顿时间 新西兰,斐济群岛 (GMT +12)</option>
								<option value="-3600">佛德尔群岛 亚速尔群岛,葡属几内亚 (GMT -1)</option>
								<option value="-7200">大西洋中部时间 格陵兰 (GMT -2)</option>
								<option value="-10800">布宜诺斯艾利斯 乌拉圭,法属圭亚那 (GMT -3)</option>
								<option value="-14400">智利巴西 委内瑞拉,玻利维亚 (GMT -4)</option>
								<option value="-18000">纽约渥太华 古巴,哥伦比亚,牙买加 (GMT -5)</option>
								<option value="-21600">墨西哥城时间 洪都拉斯,危地马拉,哥斯达黎加 (GMT -6)</option>
								<option value="-25200">美国丹佛时间 (GMT -7)</option>
								<option value="-28800">美国旧金山时间 (GMT -8)</option>
								<option value="-32400">阿拉斯加时间 (GMT -9)</option>
								<option value="-36000">夏威夷群岛 (GMT -10)</option>
								<option value="-39600">东萨摩亚群岛 (GMT -11)</option>
								<option value="-43200">艾尼威托克岛 (GMT -12)</option>
							</select>
						</li>
					</ul>
					<ul class="typecho-option" id="typecho-option-item-attachmentTypes-6">
						<li>
							<label class="typecho-label">允许上传的文件类型</label>
							<span class="multiline">
							<input name="attachmentTypes[]" type="checkbox" value="@image@" id="attachmentTypes-image" checked="true" />
							<label for="attachmentTypes-image">图片文件 <code>(gif jpg jpeg png tiff bmp)</code></label>
							</span>
							<span class="multiline">
							<input name="attachmentTypes[]" type="checkbox" value="@media@" id="attachmentTypes-media" />
							<label for="attachmentTypes-media">多媒体文件 <code>(mp3 wmv wma rmvb rm avi flv)</code></label>
							</span>
							<span class="multiline">
							<input name="attachmentTypes[]" type="checkbox" value="@doc@" id="attachmentTypes-doc" />
							<label for="attachmentTypes-doc">常用档案文件 <code>(txt doc docx xls xlsx ppt pptx zip rar pdf)</code></label>
							</span>
							<span class="multiline">
							<input name="attachmentTypes[]" type="checkbox" value="@other@" id="attachmentTypes-other" />
							<label for="attachmentTypes-other">其他格式  <input type="text" class="w-50 text-s mono" name="attachmentTypesOther" value="" /></label>
							</span>
							<p class="description">用逗号 "," 将后缀名隔开, 例如: <code>cpp, h, mak</code></p>
						</li>
					</ul>
					<ul class="typecho-option typecho-option-submit" id="typecho-option-item-submit-7">
						<li>
							<button type="submit" class="btn primary">保存设置</button>
						</li>
					</ul>
				</form>
			</div>
		</div>
	</div>
</div>
<?php $this->partial("layouts/js-common"); ?>