<div class="main">
	<div class="body container">
		<div class="typecho-page-title">
			<h2>评论设置</h2>
		</div>
		<div class="row typecho-page-main" role="form">
			<div class="col-mb-12 col-tb-8 col-tb-offset-2">
				<form action="#" method="post" enctype="application/x-www-form-urlencoded">
					<ul class="typecho-option" id="typecho-option-item-commentDateFormat-0">
						<li>
							<label class="typecho-label" for="commentDateFormat-0-1">评论日期格式</label>
							<input id="commentDateFormat-0-1" name="commentDateFormat" type="text" class="w-40 mono" value="F jS, Y \a\t h:i a" />
							<p class="description">这是一个默认的格式,当你在模板中调用显示评论日期方法时, 如果没有指定日期格式, 将按照此格式输出.<br />具体写法请参考 <a href="http://www.php.net/manual/zh/function.date.php">PHP 日期格式写法</a>.</p>
						</li>
					</ul>
					<ul class="typecho-option" id="typecho-option-item-commentsListSize-1">
						<li>
							<label class="typecho-label" for="commentsListSize-0-2">评论列表数目</label>
							<input id="commentsListSize-0-2" name="commentsListSize" type="text" class="w-20" value="10" />
							<p class="description">此数目用于指定显示在侧边栏中的评论列表数目.</p>
						</li>
					</ul>
					<ul class="typecho-option" id="typecho-option-item-commentsShow-2">
						<li>
							<label class="typecho-label">评论显示</label>
							<span class="multiline">
							<input name="commentsShow[]" type="checkbox" value="commentsShowCommentOnly" id="commentsShow-commentsShowCommentOnly" />
							<label for="commentsShow-commentsShowCommentOnly">仅显示评论, 不显示 Pingback 和 Trackback</label>
							</span>
							<span class="multiline">
							<input name="commentsShow[]" type="checkbox" value="commentsMarkdown" id="commentsShow-commentsMarkdown" />
							<label for="commentsShow-commentsMarkdown">在评论中使用Markdown语法</label>
							</span>
							<span class="multiline">
							<input name="commentsShow[]" type="checkbox" value="commentsShowUrl" id="commentsShow-commentsShowUrl" checked="true" />
							<label for="commentsShow-commentsShowUrl">评论者名称显示时自动加上其个人主页链接</label>
							</span>
							<span class="multiline">
							<input name="commentsShow[]" type="checkbox" value="commentsUrlNofollow" id="commentsShow-commentsUrlNofollow" checked="true" />
							<label for="commentsShow-commentsUrlNofollow">对评论者个人主页链接使用 <a href="#">nofollow 属性</a></label>
							</span>
							<span class="multiline">
							<input name="commentsShow[]" type="checkbox" value="commentsAvatar" id="commentsShow-commentsAvatar" checked="true" />
							<label for="commentsShow-commentsAvatar">启用 <a href="http://gravatar.com">Gravatar</a> 头像服务, 最高显示评级为 </label>
								<select id="commentsShow-commentsAvatarRating" name="commentsAvatarRating">
									<option value="G" selected="true">G - 普通</option>
									<option value="PG">PG - 13岁以上</option>
									<option value="R">R - 17岁以上成人</option>
									<option value="X">X - 限制级</option>
								</select>
							<label for="commentsShow-commentsAvatarRating"> 的头像</label>
							</span>
							<span class="multiline">
							<input name="commentsShow[]" type="checkbox" value="commentsPageBreak" id="commentsShow-commentsPageBreak" />
							<label for="commentsShow-commentsPageBreak">启用分页, 并且每页显示 </label>
							<input type="text" value="20" class="text num text-s" id="commentsShow-commentsPageSize" name="commentsPageSize" />
							<label for="commentsShow-commentsPageSize"> 篇评论, 在列出时将 </label>
							<select id="commentsShow-commentsPageDisplay" name="commentsPageDisplay">
								<option value="first">第一页</option>
								<option value="last" selected="true">最后一页</option>
							</select>
							<label for="commentsShow-commentsPageDisplay"> 作为默认显示</label>
							</span>
							<span class="multiline">
							<input name="commentsShow[]" type="checkbox" value="commentsThreaded" id="commentsShow-commentsThreaded" checked="true" />
							<label for="commentsShow-commentsThreaded">启用评论回复, 以 </label>
							<input name="commentsMaxNestingLevels" type="text" class="text num text-s" value="5" id="commentsShow-commentsMaxNestingLevels" />
							<label for="commentsShow-commentsMaxNestingLevels"> 层作为每个评论最多的回复层数</label></span>
							<span class="multiline">将
								<select id="commentsShow-commentsOrder" name="commentsOrder">
									<option value="DESC">较新的</option>
									<option value="ASC" selected="true">较旧的</option>
								</select>
							<label for="commentsShow-commentsOrder"> 的评论显示在前面</label>
							</span>
						</li>
					</ul>
					<ul class="typecho-option" id="typecho-option-item-commentsPost-3">
						<li>
							<label class="typecho-label">评论提交</label>
							<span class="multiline">
							<input name="commentsPost[]" type="checkbox" value="commentsRequireModeration" id="commentsPost-commentsRequireModeration" />
							<label for="commentsPost-commentsRequireModeration">所有评论必须经过审核</label>
							</span>
							<span class="multiline">
							<input name="commentsPost[]" type="checkbox" value="commentsWhitelist" id="commentsPost-commentsWhitelist" />
							<label for="commentsPost-commentsWhitelist">评论者之前须有评论通过了审核</label>
							</span>
							<span class="multiline">
							<input name="commentsPost[]" type="checkbox" value="commentsRequireMail" id="commentsPost-commentsRequireMail" checked="true" />
							<label for="commentsPost-commentsRequireMail">必须填写邮箱</label>
							</span>
							<span class="multiline">
							<input name="commentsPost[]" type="checkbox" value="commentsRequireURL" id="commentsPost-commentsRequireURL" />
							<label for="commentsPost-commentsRequireURL">必须填写网址</label>
							</span>
							<span class="multiline">
							<input name="commentsPost[]" type="checkbox" value="commentsCheckReferer" id="commentsPost-commentsCheckReferer" checked="true" />
							<label for="commentsPost-commentsCheckReferer">检查评论来源页 URL 是否与文章链接一致</label>
							</span>
							<span class="multiline">
							<input name="commentsPost[]" type="checkbox" value="commentsAntiSpam" id="commentsPost-commentsAntiSpam" checked="true" />
							<label for="commentsPost-commentsAntiSpam">开启反垃圾保护</label>
							</span>
							<span class="multiline">
							<input name="commentsPost[]" type="checkbox" value="commentsAutoClose" id="commentsPost-commentsAutoClose" />
							<label for="commentsPost-commentsAutoClose">在文章发布 </label>
							<input name="commentsPostTimeout" type="text" class="text num text-s" value="30" id="commentsPost-commentsPostTimeout" />
							<label for="commentsPost-commentsPostTimeout"> 天以后自动关闭评论</label>
							</span>
							<span class="multiline">
							<input name="commentsPost[]" type="checkbox" value="commentsPostIntervalEnable" id="commentsPost-commentsPostIntervalEnable" checked="true" />
							<label for="commentsPost-commentsPostIntervalEnable">同一 IP 发布评论的时间间隔限制为 </label>
							<input name="commentsPostInterval" type="text" class="text num text-s" value="1" id="commentsPost-commentsPostInterval" />
							<label for="commentsPost-commentsPostInterval"> 分钟</label>
							</span>
						</li>
					</ul>
					<ul class="typecho-option" id="typecho-option-item-commentsHTMLTagAllowed-4">
						<li>
							<label class="typecho-label" for="commentsHTMLTagAllowed-0-5">允许使用的HTML标签和属性</label>
							<textarea id="commentsHTMLTagAllowed-0-5" name="commentsHTMLTagAllowed" class="mono"></textarea>
							<p class="description">默认的用户评论不允许填写任何的HTML标签, 你可以在这里填写允许使用的HTML标签.<br />
								比如: : <code>&lt;a href=&quot;&quot;&gt; &lt;img src=&quot;&quot;&gt; &lt;blockquote&gt;</code>
							</p>
						</li>
					</ul>
					<ul class="typecho-option typecho-option-submit" id="typecho-option-item-submit-5">
						<li>
							<button type="submit" class="btn primary">保存设置</button>
						</li>
					</ul>
				</form>
			</div>
		</div>
	</div>
</div>
<?php $this->partial("layouts/js-common"); ?>