<div class="main">
	<div class="body container">
		<div class="typecho-page-title">
			<h2>阅读设置</h2>
		</div>
		<div class="row typecho-page-main" role="form">
			<div class="col-mb-12 col-tb-8 col-tb-offset-2">
				<form action="http://typecho.git.com/index.php/action/options-reading?_=3f6d33b64c8eca025e3de1983acc4f30" method="post" enctype="application/x-www-form-urlencoded">
					<ul class="typecho-option" id="typecho-option-item-postDateFormat-0">
						<li>
							<label class="typecho-label" for="postDateFormat-0-1">文章日期格式</label>
							<input id="postDateFormat-0-1" name="postDateFormat" type="text" class="w-40 mono" value="Y-m-d" />
							<p class="description">此格式用于指定显示在文章归档中的日期默认显示格式.<br />在某些主题中这个格式可能不会生效, 因为主题作者可以自定义日期格式.<br />请参考 <a href="http://www.php.net/manual/zh/function.date.php">PHP 日期格式写法</a>.</p>
						</li>
					</ul>
					<ul class="typecho-option" id="typecho-option-item-frontPage-1">
						<li>
							<label class="typecho-label">站点首页</label>
							<span class="multiline">
							<input name="frontPage" type="radio" value="recent" id="frontPage-recent" checked="true" />
								<label for="frontPage-recent">显示最新发布的文章</label>
								</span>
								<span class="multiline">
									<input name="frontPage" type="radio" value="page" id="frontPage-page" />
									<label for="frontPage-page">使用 </label>
										<select name="frontPagePage" id="frontPage-frontPagePage">
											<option value="2">关于</option>
										</select>
									<label for="frontPage-frontPagePage"> 页面作为首页</label>
								</span>
								<span class="multiline front-archive hidden">
								<input type="checkbox" id="frontArchive" name="frontArchive" value="1" />
								<label for="frontArchive">同时将文章列表页路径更改为
									<input type="text" name="archivePattern" class="w-20 mono" value="/blog/" />
								</label>
								</label>
							</span>
						</li>
					</ul>
					<ul class="typecho-option" id="typecho-option-item-postsListSize-2">
						<li>
							<label class="typecho-label" for="postsListSize-0-3">文章列表数目</label>
							<input id="postsListSize-0-3" name="postsListSize" type="text" class="w-20" value="10" />
							<p class="description">此数目用于指定显示在侧边栏中的文章列表数目.</p>
						</li>
					</ul>
					<ul class="typecho-option" id="typecho-option-item-pageSize-3">
						<li>
							<label class="typecho-label" for="pageSize-0-4">每页文章数目</label>
							<input id="pageSize-0-4" name="pageSize" type="text" class="w-20" value="5" />
							<p class="description">此数目用于指定文章归档输出时每页显示的文章数目.</p>
						</li>
					</ul>
					<ul class="typecho-option" id="typecho-option-item-feedFullText-4">
						<li>
							<label class="typecho-label">聚合全文输出</label>
							<span>
								<input name="feedFullText" type="radio" value="0" id="feedFullText-0" />
								<label for="feedFullText-0">仅输出摘要</label>
							</span>
							<span>
								<input name="feedFullText" type="radio" value="1" id="feedFullText-1" checked="true" />
								<label for="feedFullText-1">全文输出</label>
							</span>
							<p class="description">如果你不希望在聚合中输出文章全文,请使用仅输出摘要选项.<br />摘要的文字取决于你在文章中使用分隔符的位置.</p>
						</li>
					</ul>
					<ul class="typecho-option typecho-option-submit" id="typecho-option-item-submit-5">
						<li>
							<button type="submit" class="btn primary">保存设置</button>
						</li>
					</ul>
				</form>
			</div>
		</div>
	</div>
</div>
