<div id="reward-qrcode-box" class="reward-qrcode-box">
    <div class="reward-qrcode">
        <img src="http://www.marser.cn/usr/themes/marser/img/weixin.png" />
    </div>
    <div class="reward-qrcode-desc">微信扫一扫</div>
</div>
<script type='text/javascript' src='{{ static_url("layer/layer.js?_v=")~assetsVersion }}'></script>
<script type="text/javascript">
    jQuery(function($) {
        $('#reward-btn').on('click', function () {
            layer.open({
                type: 1,
                title: false,
                area:['auto', 'auto'],
                shadeClose: true,
                content: $('#reward-qrcode-box'),
            });
        })
    });
</script>