<div class="main">
	<div class="body container">
		<div class="typecho-page-title">
			<h2>插件管理</h2>
		</div>
		<div class="row typecho-page-main" role="main">
			<div class="col-mb-12 typecho-list">

				<h4 class="typecho-list-table-title">禁用的插件</h4>
				<div class="typecho-table-wrap">
					<table class="typecho-list-table deactivate">
						<colgroup>
							<col width="25%"/>
							<col width="45%"/>
							<col width="8%"/>
							<col width="10%"/>
							<col width=""/>
						</colgroup>
						<thead>
						<tr>
							<th>名称</th>
							<th>描述</th>
							<th>版本</th>
							<th>作者</th>
							<th class="typecho-radius-topright">操作</th>
						</tr>
						</thead>
						<tbody>
						<tr id="plugin-HelloWorld">
							<td>HelloWorld</td>
							<td>Hello World</td>
							<td>1.0.0</td>
							<td><a href="#">qining</a></td>
							<td><a href="#">启用</a></td>
						</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>