<div class="main">
	<div class="body container">
		<div class="typecho-page-title">
			<h2>网站外观</h2>
		</div>
		<div class="row typecho-page-main" role="main">
			<div class="col-mb-12">
				<ul class="typecho-option-tabs fix-tabs clearfix">
					<li class="current"><a href="#">可以使用的外观</a></li>
					<li><a href="#">编辑当前外观</a></li>
					<li><a href="#">设置外观</a></li>
				</ul>
				<!-- 判断操作加载 -->
				<?php $this->partial("themes/theme-index"); ?>
				<?php $this->partial("themes/options-theme"); ?>
				<?php $this->partial("themes/themes-editor"); ?>
			</div>
		</div>
	</div>
</div>