<!DOCTYPE HTML>
<html class="no-js">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">
    <meta name="renderer" content="webkit">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{title}}</title>
    <meta name="robots" content="noindex, nofollow">
    <link rel="stylesheet" href="{{ assetsUrl }}/css/normalize.css?v={{ assetsVersion }}" />
    <link rel="stylesheet" href="{{ assetsUrl }}/css/grid.css?v={{ assetsVersion }}" />
    <link rel="stylesheet" href="{{ assetsUrl }}/css/style.css?v={{ assetsVersion }}" />
    <link rel="stylesheet" href="{{ assetsUrl }}/css/admin.css?v={{ assetsVersion }}" />
    <!--[if lt IE 9]>
    <script type="text/javascript" src="{{ assetsUrl }}/js/html5shiv.js?v={{ assetsVersion }}"></script>
    <script type="text/javascript" src="{{ assetsUrl }}/js/respond.js?v={{ assetsVersion }}"></script>
    <![endif]-->
</head>
<body>
<!--[if lt IE 9]>
<div class="message error browsehappy" role="dialog">当前网页 <strong>不支持</strong> 你正在使用的浏览器. 为了正常的访问, 请 <a href="http://browsehappy.com/">升级你的浏览器</a></div>
<![endif]-->
