<div class="breadcrumbs" id="breadcrumbs">
    <ul class="breadcrumb">
        <li>
            <i class="icon-home home-icon"></i>
            <a href="{{ url(modulePathinfo~'/dashboard/index') }}">控制面板</a>
        </li>
        <li>
            <a href="{{ url(modulePathinfo~'/archives/index') }}">文章管理</a>
        </li>
    </ul>
</div>
<div class="page-content">
    <div class="col-lg-12">
        <div class="btn-panel">
            <a href="{{ url(modulePathinfo~'/archives/write') }}" class="btn btn-success btn-sm" role="button">新增文章</a>
        </div>
    </div>
</div>