<div class="breadcrumbs" id="breadcrumbs">
    <ul class="breadcrumb">
        <li>
            <i class="icon-home home-icon"></i>
            <a href="{{ url(modulePathinfo~'/dashboard/index') }}">控制面板</a>
        </li>
        <li>
            <a href="{{ url(modulePathinfo~'/archives/index') }}">文章管理</a>
        </li>
        <li>
            <a href="{{ url(modulePathinfo~'/archives/write') }}">新增文章</a>
        </li>
    </ul>
</div>
<div class="page-content">
    <form action="{{url(modulePathinfo~'/archives/saveprofile')}}" method="post" class="form-horizontal" id="save-archive-form">
        <div class="col-lg-6">
            <div class="form-group">
                <label for="archive-title" class="col-sm-2 control-label">文章标题</label>
                <div class="col-sm-9">
                    <input type="text" name="title" class="form-control" id="title">
                </div>
            </div>
            <div class="form-group">
                <label for="archive-content" class="col-sm-2 control-label">内容</label>
                <div class="col-sm-9">
                    <textarea id="article-content"></textarea>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-5">
                    <button type="submit" id="save-profile-btn" class="btn btn-info btn-sm">保存个人资料</button>
                </div>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="form-group">
                <label for="archive-time" class="col-sm-2 control-label">发布时间</label>
                <div class="col-sm-5">
                    <input type="text" name="time" id="archive-time" class="form-control Wdate" />
                </div>
            </div>
            <div class="form-group ">
                <label for="archive-category" class="col-sm-2 control-label">所属分类</label>
                <div class="col-sm-9">
                    <div class="archive-category-list">
                        <ul>
                            {% for value in categoryList %}
                            <li>
                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox" name="category[]" value="{{value['cid']}}" />{{value['category_name']}}
                                    </label>
                                </div>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label for="archive-tags" class="col-sm-2 control-label">标签</label>
                <div class="col-sm-9">
                    <input type="text" name="tags" class="form-control" id="archive-tags" placeholder="请填写标签" />
                </div>
            </div>
        </div>
    </form>
</div>
<link rel="stylesheet" href="{{ assetsUrl }}/simplemde/css/simplemde.min.css?_v={{ assetsVersion }}" />
<link rel="stylesheet" href="{{ assetsUrl }}/simplemde/css/font-awesome.min.css?_v={{ assetsVersion }}" />
<script src="{{ assetsUrl }}/simplemde/js/simplemde.min.js?_v={{ assetsVersion }}"></script>
<link rel="stylesheet" href="{{ assetsUrl }}/tagsinput/jquery.tagsinput.css?_v={{ assetsVersion }}" />
<script src="{{ assetsUrl }}/tagsinput/jquery.tagsinput.js"></script>
<script src="{{ assetsUrl }}/my97datepicker/WdatePicker.js"></script>
<script>
    var simplemde = new SimpleMDE({
        element:document.getElementById('article-content'),
        autoDownloadFontAwesome:false,
        styleSelectedText:false,
        spellChecker:false
    });
    $('#archive-time').on('click', function(){
        WdatePicker({
            dateFmt:'yyyy-MM-dd HH:mm'
        });
    });
    $('#archive-tags').tagsInput({
        'defaultText':'请填写标签',
        'width':'100%',
        'height':'auto'
    });
</script>