<div class="main">
	<div class="body container">
		<div class="typecho-page-title">
			<h2>创建新页面</h2>
		</div>
		<div class="row typecho-page-main typecho-post-area" role="form">
			<form action="#" method="post" name="write_page">
				<div class="col-mb-12 col-tb-9" role="main">

					<p class="title">
						<label for="title" class="sr-only">标题</label>
						<input type="text" id="title" name="title" autocomplete="off" value="" placeholder="标题" class="w-100 text title" />
					</p>
					<p class="mono url-slug">
						<label for="slug" class="sr-only">网址缩略名</label>
						typecho.git.com/index.php/<input type="text" id="slug" name="slug" autocomplete="off" value="" class="mono" />.html                    </p>
					<p>
						<label for="text" class="sr-only">页面内容</label>
						<textarea style="height: 350px" autocomplete="off" id="text" name="text" class="w-100 mono"></textarea>
					</p>

					<section id="custom-field" class="typecho-post-option fold">
						<label id="custom-field-expand" class="typecho-label"><a href="##"><i class="i-caret-right"></i> 自定义字段</a></label>
						<table class="typecho-list-table mono">
							<colgroup>
								<col width="25%"/>
								<col width="10%"/>
								<col width="55%"/>
								<col width="10%"/>
							</colgroup>
							<tr>
								<td>
									<label for="fieldname" class="sr-only">字段名称</label>
									<input type="text" name="fieldNames[]" placeholder="字段名称" id="fieldname" class="text-s w-100">
								</td>
								<td>
									<label for="fieldtype" class="sr-only">字段类型</label>
									<select name="fieldTypes[]" id="fieldtype">
										<option value="str">字符</option>
										<option value="int">整数</option>
										<option value="float">小数</option>
									</select>
								</td>
								<td>
									<label for="fieldvalue" class="sr-only">字段值</label>
									<textarea name="fieldValues[]" placeholder="字段值" id="fieldvalue" class="text-s w-100" rows="2"></textarea>
								</td>
								<td>
									<button type="button" class="btn btn-xs">删除</button>
								</td>
							</tr>
						</table>
						<div class="description clearfix">
							<button type="button" class="btn btn-xs operate-add">+添加字段</button>
							自定义字段可以扩展你的模板功能, 使用方法参见 <a href="#">帮助文档</a>                        </div>
					</section>
					<p class="submit clearfix">
                        <span class="right">
                            <input type="hidden" name="cid" value="" />
                            <button type="submit" name="do" value="save" id="btn-save" class="btn">保存草稿</button>
                            <button type="submit" name="do" value="publish" class="btn primary" id="btn-submit">发布页面</button>
	                        <input type="hidden" name="markdown" value="1" />
                        </span>
					</p>

				</div>
				<div id="edit-secondary" class="col-mb-12 col-tb-3" role="complementary">
					<ul class="typecho-option-tabs clearfix">
						<li class="active w-50"><a href="#tab-advance">选项</a></li>
						<li class="w-50"><a href="#tab-files" id="tab-files-btn">附件</a></li>
					</ul>

					<div id="tab-advance" class="tab-content">
						<section  class="typecho-post-option" role="application">
							<label for="date" class="typecho-label">发布日期</label>
							<p><input class="typecho-date w-100" type="text" name="date" id="date" value="" /></p>
						</section>

						<section class="typecho-post-option">
							<label for="order" class="typecho-label">页面顺序</label>
							<p><input type="text" id="order" name="order" value="" class="w-100" /></p>
							<p class="description">为你的自定义页面设定一个序列值以后, 能够使得它们按此值从小到大排列</p>
						</section>

						<section  class="typecho-post-option">
							<label for="template" class="typecho-label">自定义模板</label>
							<p>
								<select name="template" id="template">
									<option value="">不选择</option>
								</select>
							</p>
							<p class="description">如果你为此页面选择了一个自定义模板, 系统将按照你选择的模板文件展现它</p>
						</section>


						<button type="button" id="advance-panel-btn" class="btn btn-xs">高级选项 <i class="i-caret-down"></i></button>
						<div id="advance-panel">
							<section class="typecho-post-option visibility-option">
								<label for="visibility" class="typecho-label">公开度</label>
								<p>
									<select id="visibility" name="visibility">
										<option value="publish" selected>公开</option>
										<option value="hidden">隐藏</option>
									</select>
								</p>
							</section>

							<section class="typecho-post-option allow-option">
								<label class="typecho-label">权限控制</label>
								<ul>
									<li><input id="allowComment" name="allowComment" type="checkbox" value="1" checked="true" />
										<label for="allowComment">允许评论</label></li>
									<li><input id="allowPing" name="allowPing" type="checkbox" value="1" checked="true" />
										<label for="allowPing">允许被引用</label></li>
									<li><input id="allowFeed" name="allowFeed" type="checkbox" value="1" checked="true" />
										<label for="allowFeed">允许在聚合中出现</label></li>
								</ul>
							</section>

						</div>
					</div>
					<div id="tab-files" class="tab-content hidden">
						<div id="upload-panel" class="p">
							<div class="upload-area" draggable="true">拖放文件到这里<br>或者 <a href="###" class="upload-file">选择文件上传</a></div>
							<ul id="file-list">
							</ul>
						</div>

					</div>
				</div>
			</form>
		</div>
	</div>
</div>
<?php $this->partial("js/js-write-page"); ?>