<div class="main">
	<div class="body container">
		<div class="typecho-page-title">
			<h2>撰写新文章</h2>
		</div>
		<div class="row typecho-page-main typecho-post-area" role="form">
			<form action="{{url(modulePathinfo~"/archives/add")}}" method="post" name="write_post">
				<div class="col-mb-12 col-tb-9" role="main">
					<p class="title">
						<label for="title" class="sr-only">标题</label>
						<input type="text" id="title" name="title" autocomplete="off" value="" placeholder="标题" class="w-100 text title" />
					</p>
					<p class="mono url-slug">
						<label for="slug" class="sr-only">网址缩略名</label>/archives/{aid}/
					</p>
					<p>
						<label for="content" class="sr-only">文章内容</label>
						<textarea style="height: 350px" autocomplete="off" id="text" name="content" class="w-100 mono"></textarea>
					</p>
					<p class="submit clearfix">
                        <span class="right">
                            <input type="hidden" name="cid" value="" />
                            <button type="submit" name="do" value="save" id="btn-save" class="btn">保存草稿</button>
                            <button type="submit" name="do" value="publish" class="btn primary" id="btn-submit">发布文章</button>
	                        <input type="hidden" name="markdown" value="1" />
                        </span>
					</p>

				</div>

				<div id="edit-secondary" class="col-mb-12 col-tb-3" role="complementary">
					<ul class="typecho-option-tabs clearfix">
						<li class="active w-50"><a href="#tab-advance">选项</a></li>
						<li class="w-50"><a href="#tab-files" id="tab-files-btn">附件</a></li>
					</ul>


					<div id="tab-advance" class="tab-content">
						<section class="typecho-post-option" role="application">
							<label for="date" class="typecho-label">发布日期</label>
							<p><input class="typecho-date w-100" type="text" name="date" id="date" value="" /></p>
						</section>

						<section class="typecho-post-option category-option">
							<label class="typecho-label">分类</label>
							<ul>
								<li><input type="checkbox" id="category-1" value="1" name="category[]" />
									<label for="category-1">默认分类</label></li>
							</ul>
						</section>

						<section class="typecho-post-option">
							<label for="token-input-tags" class="typecho-label">标签</label>
							<p><input id="tags" name="tags" type="text" value="" class="w-100 text" /></p>
						</section>
					</div>

					<div id="tab-files" class="tab-content hidden">
						<div id="upload-panel" class="p">
							<div class="upload-area" draggable="true">拖放文件到这里<br>或者 <a href="###" class="upload-file">选择文件上传</a></div>
							<ul id="file-list">
							</ul>
						</div>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
<?php $this->partial("js/js-write-post"); ?>
