<div class="breadcrumbs" id="breadcrumbs">
    <ul class="breadcrumb">
        <li>
            <i class="icon-home home-icon"></i>
            <a href="{{ url(modulePathinfo~'/dashboard/index') }}">控制面板</a>
        </li>
        <li>
            <a href="{{ url(modulePathinfo~'/archives/index') }}">文章管理</a>
        </li>
        <li>
            <a href="{{ url(modulePathinfo~'/archives/write') }}">新增文章</a>
        </li>
    </ul>
</div>
<div class="page-content">
    <div class="col-lg-12">
        <ul class="nav nav-tabs">
            <li class="active">
                <a href="#base" data-toggle="tab">基础</a>
            </li>
            <li>
                <a href="#extension" data-toggle="tab">扩展</a>
            </li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane fade in active" id="base">
                <form action="{{url(modulePathinfo~'/archives/saveprofile')}}" method="post" class="form-horizontal" id="save-archive-form">
                    <div class="form-group">
                        <label for="archive-title" class="col-sm-2 control-label">文章标题</label>
                        <div class="col-sm-5">
                            <input type="text" name="title" class="form-control" id="title">
                        </div>
                    </div>
                    <div class="form-group ">
                        <label for="archive-category" class="col-sm-2 control-label">所属分类</label>
                        <div class="col-sm-5">
                            <select class="form-control" name="cid">
                                <option>请选择</option>
                                {% for value in categoryList %}
                                    <option value="{{value['cid']}}">
                                        {% if value['parent_cid'] > 0 %}
                                            {{ str_repeat('&nbsp;&nbsp;', substr_count(value['path'], '/')) }}{{value['category_name']}}
                                        {% else %}
                                            {{value['category_name']}}
                                        {% endif %}
                                    </option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="archive-content" class="col-sm-2 control-label">内容</label>
                        <div class="col-sm-5">

                        </div>
                    </div>
                    <div class="form-group">
                        <label for="archive-tags" class="col-sm-2 control-label">标签</label>
                        <div class="col-sm-5">
                            <input type="text" name="tags" class="form-control" id="archive-tags" placeholder="请填写电子邮箱地址" />                      </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-5">
                            <button type="submit" id="save-profile-btn" class="btn btn-info btn-sm">保存个人资料</button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="tab-pane fade" id="extension">
                <form action="{{url(modulePathinfo~'/account/savepwd')}}" method="post" class="form-horizontal" id="save-password-form">
                    <div class="form-group ">
                        <label for="old-password" class="col-sm-2 control-label">原始密码</label>
                        <div class="col-sm-5">
                            <input type="password" name="oldpwd" class="form-control" id="old-password" autocomplete="off" placeholder="请填写原始密码">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="new-password" class="col-sm-2 control-label">新密码</label>
                        <div class="col-sm-5">
                            <input type="password" name="newpwd" class="form-control" id="new-password" placeholder="请填写新密码" autocomplete="off" />
                            <span class="form-tips">密码由6-20个字符组成</span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="confirm-password" class="col-sm-2 control-label">确认密码</label>
                        <div class="col-sm-5">
                            <input type="password" name="confirmpwd" class="form-control" id="confirm-password" placeholder="请再次填写新密码" autocomplete="off" />
                            <span class="form-tips">与上面输入的新密码保持一致</span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-5">
                            <button type="submit" id="save-password-btn" class="btn btn-info btn-sm">修改密码</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>