<script src="{{ assetsUrl }}/ace/js/ace.min.js?_v={{ assetsVersion }}"></script>
<script src="{{ assetsUrl }}/treegrid/js/jquery.treegrid.js?_v={{ assetsVersion }}"></script>
<script src="{{ assetsUrl }}/assets/js/public.js?_v={{ assetsVersion }}"></script>

<script>
    $('.tree-grid').treegrid({
        expanderExpandedClass: 'glyphicon glyphicon-minus',
        expanderCollapsedClass: 'glyphicon glyphicon-plus',
    });
</script>