<script src="{{ assetsUrl }}/js/jquery-2.0.3.min.js?_v={{ assetsVersion }}"></script>
<script src="{{ assetsUrl }}/js/bootstrap.min.js?_v={{ assetsVersion }}"></script>
<script src="{{ assetsUrl }}/js/ace-elements.min.js?_v={{ assetsVersion }}"></script>
<script src="{{ assetsUrl }}/js/ace.min.js?_v={{ assetsVersion }}"></script>
<script src="{{ assetsUrl }}/js/jquery.treegrid.js?_v={{ assetsVersion }}"></script>
<script src="{{ assetsUrl }}/js/bootstrap-editable.min.js?_v={{ assetsVersion }}"></script>
<script src="{{ assetsUrl }}/js/public.js?_v={{ assetsVersion }}"></script>

<link href="{{ assetsUrl }}/css/bootstrap-editable.css?_v={{ assetsVersion }}" rel="stylesheet"/>

<script>
    $('.tree-grid').treegrid({
        expanderExpandedClass: 'glyphicon glyphicon-minus',
        expanderCollapsedClass: 'glyphicon glyphicon-plus',
    });
</script>