<script src="{{ assetsUrl }}/bootstrap/js/bootstrap.min.js?_v={{ assetsVersion }}"></script>
<script src="{{ assetsUrl }}/ace/js/ace.min.js?_v={{ assetsVersion }}"></script>
<script src="{{ assetsUrl }}/treegrid/js/jquery.treegrid.js?_v={{ assetsVersion }}"></script>
<script src="{{ assetsUrl }}/bootstrap-editable/js/bootstrap-editable.min.js?_v={{ assetsVersion }}"></script>
<script src="{{ assetsUrl }}/assets/js/public.js?_v={{ assetsVersion }}"></script>

<link href="{{ assetsUrl }}/bootstrap-editable/css/bootstrap-editable.css?_v={{ assetsVersion }}" rel="stylesheet"/>

<script>
    $('.tree-grid').treegrid({
        expanderExpandedClass: 'glyphicon glyphicon-minus',
        expanderCollapsedClass: 'glyphicon glyphicon-plus',
    });
</script>