<meta charset="utf-8" />
<title>{{title}}</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<script src="{{ assetsUrl }}/ace/js/jquery-2.0.3.min.js?_v={{ assetsVersion }}"></script>
<link href="{{ assetsUrl }}/bootstrap/css/bootstrap.min.css?_v={{ assetsVersion }}" rel="stylesheet" />
<link rel="stylesheet" href="{{ assetsUrl }}/ace/css/font-awesome.min.css?_v={{ assetsVersion }}" />
<link href="{{ assetsUrl }}/assets/css/style.css?_v={{ assetsVersion }}" rel="stylesheet" />

<link rel="stylesheet" href="{{ assetsUrl }}/ace/css/ace.min.css?_v={{ assetsVersion }}" />
<script src="{{ assetsUrl }}/ace/js/ace-extra.min.js?_v={{ assetsVersion }}"></script>