<meta charset="utf-8" />
<title>{{title}}</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<link href="{{ assetsUrl }}/css/bootstrap.min.css?_v={{ assetsVersion }}" rel="stylesheet" />
<link rel="stylesheet" href="{{ assetsUrl }}/css/font-awesome.min.css?_v={{ assetsVersion }}" />
<link href="{{ assetsUrl }}/css/style.css?_v={{ assetsVersion }}" rel="stylesheet" />

<link rel="stylesheet" href="{{ assetsUrl }}/css/ace.min.css?_v={{ assetsVersion }}" />
<script src="{{ assetsUrl }}/js/ace-extra.min.js?_v={{ assetsVersion }}"></script>