<div class="main">
	<div class="body container">
		<div class="typecho-page-title">
			<h2>编辑分类 默认分类</h2>
		</div>
		<div class="row typecho-page-main" role="form">
			<div class="col-mb-12 col-tb-6 col-tb-offset-3">
				<form action="#" method="post" enctype="application/x-www-form-urlencoded">
					<ul class="typecho-option" id="typecho-option-item-name-0">
						<li>
							<label class="typecho-label" for="name-0-1">分类名称 *</label>
							<input id="name-0-1" name="name" type="text" class="text" value="默认分类" />
						</li>
					</ul>
					<ul class="typecho-option" id="typecho-option-item-slug-1">
						<li>
							<label class="typecho-label" for="slug-0-2">分类缩略名</label>
							<input id="slug-0-2" name="slug" type="text" class="text" value="default" />
							<p class="description">分类缩略名用于创建友好的链接形式, 建议使用字母, 数字, 下划线和横杠.</p>
						</li>
					</ul>
					<ul class="typecho-option" id="typecho-option-item-parent-2">
						<li>
							<label class="typecho-label" for="parent-0-3">父级分类</label>
							<select name="parent" id="parent-0-3">
								<option value="0" selected="true">不选择</option>
							</select>
							<p class="description">此分类将归档在您选择的父级分类下.</p>
						</li>
					</ul>
					<ul class="typecho-option" id="typecho-option-item-description-3">
						<li>
							<label class="typecho-label" for="description-0-4">分类描述</label>
							<textarea id="description-0-4" name="description">只是一个默认分类</textarea>
							<p class="description">此文字用于描述分类, 在有的主题中它会被显示.</p>
						</li>
					</ul>
					<ul class="typecho-option" id="typecho-option-item-do-4" style="display:none">
						<li>
							<input name="do" type="hidden" value="update" />
						</li>
					</ul>
					<ul class="typecho-option" id="typecho-option-item-mid-5" style="display:none">
						<li>
							<input name="mid" type="hidden" value="1" />
						</li>
					</ul>
					<ul class="typecho-option typecho-option-submit" id="typecho-option-item--6">
						<li>
							<button type="submit" class="btn primary">编辑分类</button>
						</li>
					</ul>
				</form>
			</div>
		</div>
	</div>
</div>